config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'store/index'

  get 'store/interfata_angular'

  resources :products

  root :to => 'store#index', :as => 'store'

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy, :index]

  # GET /carts
  # GET /carts.json
  def index
    @cart = current_cart
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = current_cart
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to current_cart, notice: 'Cosul de cumparaturi a fost sters cu succes' }
      format.json { head :no_content }
    end
  end

  private

    def set_cart
      @cart = Cart.find_by_id(params[:id])
    end

    def cart_params
      params[:cart]
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-md-4 col-md-offset-4">
    <p> Lista produse din cosul de cumparaturi </p>
  </div>
  
  <% for item in @cart.line_items %>

    <div class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
      <div class="thumbnail" >
        <%= image_tag(item.product.image_url, :class => "img-responsive") %>
        <div class="caption">
          <div class="row">
            <div class="col-md-6 col-xs-6">
                  <h3><%= item.product.title %></h3>
            </div>
            <div class="col-md-6 col-xs-6 price">
              <h3>
                <label>Pret <%= number_to_currency(item.product.price) %></label>
              </h3>
            </div>
          </div>

          <p><%= item.product.description %></p>
      
        </div>
      </div>
    </div>
  <% end %>

</div>

<div class="row">

  <div class="col-md-4 col-md-offset-4">

    <%= button_to 'Sterge cosul', @cart, :method => :delete, :confirm => 'Esti sigur ca vrei sa stergi cosul de cumparaturi?', :class => "btn btn-success btn-product" %>
    <%= button_to 'Check out', @cart, :method => :delete, :confirm => 'Esti sigur ca vrei sa cumperi toate produsele din cosul de cumparaturi?', :class => "btn btn-success btn-product" %>

  </div>

</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <div class="col-md-4 col-md-offset-4">
    <p> Lista produse din cosul de cumparaturi </p>
  </div>
  
  <% for item in @cart.line_items %>

    <div class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
      <div class="thumbnail" >
        <%= image_tag(item.product.image_url, :class => "img-responsive") %>
        <div class="caption">
          <div class="row">
            <div class="col-md-6 col-xs-6">
                  <h3><%= item.product.title %></h3>
            </div>
            <div class="col-md-6 col-xs-6 price">
              <h3>
                <label>Pret <%= number_to_currency(item.product.price) %></label>
              </h3>
            </div>
          </div>

          <p><%= item.product.description %></p>
      
        </div>
      </div>
    </div>
  <% end %>

</div>

<div class="row">

  <div class="col-md-4 col-md-offset-4">

    <%= button_to 'Sterge cosul', @cart, :method => :delete, :confirm => 'Esti sigur ca vrei sa stergi cosul de cumparaturi?', :class => "btn btn-success btn-product" %>
    <%= button_to 'Check out', @cart, :method => :delete, :confirm => 'Esti sigur ca vrei sa cumperi toate produsele din cosul de cumparaturi?', :class => "btn btn-success btn-product" %>

  </div>

</div>