config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'store/index'

  get 'store/interfata_angular'

  resources :products

  root :to => 'store#index', :as => 'store'

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :line_items
	before_destroy :nu_sterge_daca_e_in_cart

	validates :title, :description, :image_url, :price, :quantity, :presence => true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01, :message => "Pretul produsului trebuie sa fie mai mare sau egal cu 0.1"}
	validates :quantity, :numericality => {:greater_than_or_equal_to => 1, :message => "Cantitatea disponibila initial trebuie sa fie mai mare sau egala cu 1"}
	validates :title, :uniqueness => {:message => "Produsul exista deja in magazin. Cresteti stocul produsului existent sau redunimiti produsul curent."}
	#validates :image_url, format: {
    # with: %r{\.(gif|jpg|png)$}i,
    #  message: 'Imaaginea trebuie sa fie de tip gif, jpg sau png'
  	#}

  	def nu_sterge_daca_e_in_cart
  		if line_items.count.zero?
  			return true
  		else
  			return false
  		end
  	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_produc, only: [:show, :edit, :update, :destroy]

  before_action :utilizatorul_este_admin

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(Product.arel_table[:quantity].gt(0)).all#find(:all, :conditions => ['quantity > ?', 0])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(produc_params)

      if @product.save
        redirect_to store_url
      end
    
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(produc_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to producs_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

    def utilizatorul_este_admin
      utilizator = User.find_by_id(session[:user_id])
      unless utilizator.role == "administrator"
        redirect_to store_url
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produc
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produc_params
      params.require(:product).permit(:title, :description, :image_url, :price, :quantity)
    end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this produc from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_produc_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_produc_path(@product) %> |
<%= link_to 'Back', products_path %>